/*
	Banking using Array of Structures (Structures and Unions)
		Write a C Program to simulate Banking application that performs insertion, deletion and search on array of customer structures that includes AC No., Name, Mobile No, Address etc.
*/
#include <stdio.h>
#include <string.h>

#define ARR_SIZE	3
#define NAME_SIZE	50
#define ADD_SIZE	100
#define BASE_AC_NO	2034349800

int count = 0, last = 0;

struct customer
{
	long contact, account_num;
	char name[NAME_SIZE], address[ADD_SIZE];
};

void insert_customer_data (struct customer s[])
{
	if (index == ARR_SIZE)
		printf ("\t\t\t!!! Customer Records Full !!!\n");
	else
	{
		getchar ();
		printf ("\tName         : ");
		gets (s[index]->name);
		s[index]->account_num = BASE_AC_NO + count;
		printf ("\tAccount No.  : %li (Generated by the system)", s[index]->account_num);
		printf ("\tAddress      : ");
		gets (s[index]->address);
		printf ("\tContact      : ");
		scanf ("%li", &s[index]->contact);
		while ((s[index]->contact / 10000000000) || (s[index]->contact / 1000000000 == 0))
		{
			printf ("\t\t\t\tRe-Enter contact correctly\n");
			printf ("\tContact      : ");
			scanf ("%li", &s[index]->contact);
		}
		count++;
		index++;
	}
}

void search_customer_data (struct customer s[])
{
	if (index == 0)
		printf ("\t\t\t!!! No Customer Data Available To Search For !!!\n");
	else
	{
		int param_choice;
		printf ("\nWhat do you wish to search by :
					\n\t1. Customer Name
					\n\t2. Account number
					\n\t3. Address
					\n\t4. Contact
					\n\t----> ");
		scanf ("%d", &param_choice);
		switch (param_choice)
		{
			case 1	: 
					break;
			case 2 	: 
					break;
			case 3	: 
					break;
			case 4	: 
					break;
		}
	}
}

void delete_customer_data (struct customer s[])
{
	if (index == 0)
		printf ("\t\t\t!!! No Customer Data available to delete !!!\n");
	else
	{
		long account_num;
		printf ("Enter the account number to delete : ");
		scanf ("%li", account_num);
		int flag = -1;
		for (int i = 0; i < index; ++i)
		{
			/* code */
		}
		if (flag != -1)
			index--;
		else
			printf ("\t\t\t!!! Account Number doesn't exist !!!\n");
	}
}

void print_customer_data (struct customer s)
{
	printf ("\t %s holding Ac No - %li lives at %s. Contact : %li\n", s.name, s.account_num, s.address, s.contact);
}

int main ()
{
	int choice_op, flag = 'y';
	struct customer ct[ARR_SIZE];

	while (flag == 'y' || flag == 'Y')
	{
		printf ("\nChoose Operation :
					\n\t1. Insert Customer Data
					\n\t2. Search Customer Data
					\n\t3. Delete Customer Data
					\n\t----> ");
		scanf ("%d", &choice_op);

		switch (choice_op)
		{
			case 1	: insert_customer_data (ct);
					break;
			case 2	: search_customer_data (ct);
					break;
			case 3	: delete_customer_data (ct);
					break;
			default	: printf ("\t\t\t\t!!! INVALID CHOICE !!!");
		}

		printf ("\n\t\t\tTo continue, press 'y' or 'Y' (any other character to exit) : ");
		scanf ("%c", flag);
	}

	printf ("\t\t\tThankyou for trying this program !!!\n", );

	return 0;
}
